// Regenerates the task-progress section of PROJECT_MAP.html from the "- [x] Done" boxes in
// docs/backlog.md. Runs from the lefthook pre-commit hook whenever docs/backlog.md is committed,
// or by hand with `pnpm map`.
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const backlog = readFileSync(new URL('docs/backlog.md', root), 'utf8');
const mapUrl = new URL('PROJECT_MAP.html', root);
const map = readFileSync(mapUrl, 'utf8');

// Each task section starts with "## <ID>: <title>" followed by a "- [ ] Done" / "- [x] Done" line.
const tasks = [];
const re = /^## (Task 0|P1-\d{2}):[^\n]*\n+- \[( |x|X)\] Done/gm;
for (const m of backlog.matchAll(re)) tasks.push({ id: m[1], done: m[2] !== ' ' });

const TRACKS = [
  ['پایه', 'ابزار و CI', ['Task 0']],
  ['موتور', 'منطق محصول', [1, 2, 3, 4, 5, 6]],
  ['خواندن فایل', 'CSV و Excel', [7, 8, 9, 10, 11]],
  ['اسکلت سایت', 'زبان، طراحی، انتشار', [12, 13, 14]],
  ['دمو', 'صفحه اصلی محصول', [15, 16, 17, 18, 19, 20]],
  ['صفحه معرفی', 'landing و SEO', [21, 22, 23]],
  ['قانونی و انتشار', 'تماس، امنیت، دامنه', [24, 25, 26, 27, 28]],
];
const idOf = (n) => (typeof n === 'number' ? `P1-${String(n).padStart(2, '0')}` : n);
const status = new Map(tasks.map((t) => [t.id, t.done]));
const next = tasks.find((t) => !t.done)?.id;
const doneCount = tasks.filter((t) => t.done).length;
const fa = (n) => String(n).replace(/\d/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[Number(d)]);

const chip = (id) => {
  const cls = status.get(id) ? 'chip done' : id === next ? 'chip next' : 'chip';
  return `<span class="${cls}">${id}</span>`;
};
const rows = TRACKS.map(
  ([name, sub, ids]) =>
    `    <div class="track"><div class="name">${name}<small>${sub}</small></div><div class="chips">${ids
      .map((n) => chip(idOf(n)))
      .join('')}</div></div>`,
).join('\n');

const stamp = new Date().toISOString().slice(0, 10);
const summary = `  <p class="lead"><b>${fa(doneCount)} از ${fa(tasks.length)}</b> تسک تمام شده${
  next ? ` · تسک بعدی: <span class="f">${next}</span>` : ' · همه تمام شد!'
} · به‌روزرسانی: <span class="f">${stamp}</span></p>`;

const block = `<!-- TASKS:START (generated by scripts/update-map.mjs, do not edit by hand) -->\n${summary}\n  <div class="tracks">\n${rows}\n  </div>\n  <!-- TASKS:END -->`;
const updated = map.replace(/<!-- TASKS:START[\s\S]*?<!-- TASKS:END -->/, block);
if (updated === map && !map.includes('TASKS:START')) {
  console.error('PROJECT_MAP.html has no TASKS:START/END markers; nothing updated.');
  process.exit(1);
}
writeFileSync(mapUrl, updated);
console.log(`PROJECT_MAP.html: ${doneCount}/${tasks.length} done, next ${next ?? '-'}`);
