/**
 * Copies the prototype's sample CSVs (`reference/python-prototype/sample_data{,_de}`) into
 * `src/generated/<locale>.ts`, with `asOf` from the matching golden file (backlog P1-11).
 *
 * The CSVs become string literals, not `.csv` assets, so every bundler (Next.js, Vitest) imports
 * them the same way. Every character that git, editors or Prettier could change (BOM, CR, tab,
 * non-ASCII) is written as an escape, so the file is plain ASCII and `TextEncoder` turns each
 * `content` back into exactly the reference bytes (checked by `test/datasets.test.ts`).
 *
 *   node scripts/sync-reference.ts          rewrite src/generated/
 *   node scripts/sync-reference.ts --check  exit 1 if src/generated/ is out of date (CI)
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const PROTOTYPE = new URL('../../../reference/python-prototype/', import.meta.url);
const GENERATED = new URL('../src/generated/', import.meta.url);
const SOURCES = { de: 'sample_data_de', en: 'sample_data' } as const;

const SHORT_ESCAPES: Readonly<Record<string, string>> = { '\r': '\\r', '\n': '\\n', '\t': '\\t' };

function escapeLiteral(text: string): string {
  return text.replace(
    /[^\x20-\x7e]|['\\]/gu,
    (ch) => SHORT_ESCAPES[ch] ?? `\\u{${(ch.codePointAt(0) ?? 0).toString(16)}}`,
  );
}

function readAsOf(folder: string): string {
  const golden: unknown = JSON.parse(
    readFileSync(new URL(`golden/${folder}.json`, PROTOTYPE), 'utf8'),
  );
  const asOf =
    typeof golden === 'object' && golden !== null && 'asOf' in golden ? golden.asOf : null;
  if (typeof asOf !== 'string' || !/^\d{4}-\d{2}-\d{2}$/u.test(asOf)) {
    throw new Error(`golden/${folder}.json: missing or invalid asOf`);
  }
  return asOf;
}

function renderModule(locale: string, folder: string): string {
  const dir = new URL(`${folder}/`, PROTOTYPE);
  const names = readdirSync(dir)
    .filter((name) => name.endsWith('.csv'))
    .sort();
  const files = names.map((name) => {
    // `ignoreBOM` keeps the BOM as U+FEFF; `fatal` rejects a non-UTF-8 reference file.
    const content = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true }).decode(
      readFileSync(new URL(name, dir)),
    );
    // One literal per CSV line keeps diffs of the generated file readable.
    const lines = content.split(/(?<=\n)/u).map((line) => `'${escapeLiteral(line)}'`);
    return `    {\n      name: '${name}',\n      content:\n        ${lines.join(' +\n        ')},\n    },`;
  });
  return [
    `// Generated by scripts/sync-reference.ts from reference/python-prototype/${folder}. Do not edit.`,
    "import type { IsoDate } from '@vorchain/engine';",
    '',
    "import type { SampleDataset } from '../dataset.ts';",
    '',
    `export const ${locale}: SampleDataset = {`,
    `  // Checked against /^\\d{4}-\\d{2}-\\d{2}$/ by the generator; taken from golden/${folder}.json.`,
    `  asOf: '${readAsOf(folder)}' as IsoDate,`,
    '  files: [',
    ...files,
    '  ],',
    '};',
    '',
  ].join('\n');
}

const check = process.argv.includes('--check');
const stale: string[] = [];
for (const [locale, folder] of Object.entries(SOURCES)) {
  const target = new URL(`${locale}.ts`, GENERATED);
  const expected = renderModule(locale, folder);
  if (!check) {
    writeFileSync(target, expected);
    continue;
  }
  let actual = '';
  try {
    actual = readFileSync(target, 'utf8');
  } catch {
    // A missing file counts as stale.
  }
  if (actual !== expected) stale.push(`src/generated/${locale}.ts`);
}

if (stale.length > 0) {
  console.error(
    `Out of date with reference/python-prototype: ${stale.join(', ')}.\n` +
      'Run `pnpm --filter @vorchain/sample-data sync` and commit the result.',
  );
  process.exit(1);
}
